exclude: (^notebooks/)
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        args: [--fix, --exit-non-zero-on-fix]
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: (^docs/)
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)
