site_name: Pipes
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How To's: how-to.md
  - Reference:
      - Pipeline: pipeline-ref.md
      - PipeProcessor: processor-ref.md
theme:
  name: material
  features:
    - content.code.copy
repo_url: https://github.com/chris-santiago/pipes
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]
          options:
            show_root_full_path: true
            show_submodules: true
            docstring_style: numpy
            merge_init_into_class: true
markdown_extensions:
  # For Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # For Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
